# Generated by Django 4.1.7 on 2023-03-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edition_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
    ]
