# Generated by Django 4.1.7 on 2023-03-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Содержимое')),
                ('creation_date', models.DateField(auto_now=True, verbose_name='Дата создания комментария')),
                ('edition_date', models.DateTimeField(verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=500, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Wlog_image/', verbose_name='Изображение')),
                ('creation_date', models.DateField(auto_now=True, verbose_name='Дата создания поста')),
                ('edition_date', models.DateTimeField(verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
